

all:
	#g++ Principal.cpp -I/home/vlarobbyk/aplicaciones/Librerias/opencv-4.0.0/opencv4-installation/include/opencv4/ -L/home/vlarobbyk/aplicaciones/Librerias/opencv-4.0.0/opencv4-installation/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -o vision.bin
	g++ Principal.cpp -I/usr/local/include/opencv4/ -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -o vision.bin
	
run:
	./vision.bin
	
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/vlarobbyk/aplicaciones/Librerias/opencv-4.0.0/opencv4-installation/lib/
#export LD_LIBRARY_PATH
